# Use an official Python runtime as a base image
FROM python:3.12

LABEL maintainer="muhammad-ahad"

# Set the working directory inside the container
WORKDIR /code

# Environment variable to prevent buffering logs
ENV PYTHONUNBUFFERED=1

# Install system dependencies required for some Python packages
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Install Poetry globally
RUN pip install poetry

# Copy only dependency files first (to leverage Docker caching)
COPY pyproject.toml poetry.lock ./

# Avoid virtual environments inside the container
RUN poetry config virtualenvs.create false

# Ensure poetry.lock is up-to-date before installing dependencie
RUN poetry install --no-root

# Copy the rest of the project files into the container
COPY . /code/

# Expose the FastAPI port
EXPOSE 8000

# Command to start the FastAPI application
CMD ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
